version: "3.5"
services:
  app:
    image: monitoring-demo
    container_name: monitoring-demo
    build:
      context: ./
    ports:
    - "8080:8080"
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
    - ./monitoring/prometheus/:/etc/prometheus/
    ports:
    - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - "3000:3000"
    volumes:
    - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
    - ./monitoring/grafana/config.monitoring
    depends_on:
    - prometheus
